import {loadAppConfig,loadDashboardData} from './data-service.js';
import {STROKE_ORDER,compareRows,currentAge,distanceSortValue,eventKey,eventLabel,firstRecord,formatDate,formatSwimTime,formatTimeOnly,latestRecord,pbMap,unique} from './utils.js';
import {badgeHtml,evaluateStandard,getAgeBracket,getStandardTable} from './standards.js';
import {renderPBProgress,renderProgressChart,renderRadar,resizeCharts} from './charts.js';

let swimmerDoc,profile,records=[],goals=[],standards,directory;
let progressCourse='M',sortState={field:'date',direction:'desc'},historyPage=1,historyPageSize=25;
const $=id=>document.getElementById(id);
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function selected(){return {year:$('year').value,stroke:$('stroke').value,course:$('course').value,distance:$('distance').value}}
function filteredRecords(){const f=selected();return records.filter(r=>(f.year==='All'||String(r.year)===f.year)&&(f.stroke==='All'||r.stroke===f.stroke)&&(f.course==='All'||r.course===f.course)&&(f.distance==='All'||eventLabel(r)===f.distance))}
function matchingGoals(){const f=selected();return goals.filter(g=>(f.stroke==='All'||g.stroke===f.stroke)&&(f.course==='All'||g.course===f.course)&&(f.distance==='All'||eventLabel(g)===f.distance))}
function currentPB(stroke,course,distance,source=records){const rs=source.filter(r=>r.stroke===stroke&&r.course===course&&Number(r.distance)===Number(distance));return rs.length?Math.min(...rs.map(r=>r.time)):null}
function goalProgress(g){const first=firstRecord(records,g.stroke,g.course,g.distance),pb=currentPB(g.stroke,g.course,g.distance);if(pb==null||!first)return {baseline:first?.time??null,pb,percent:0,remaining:null,met:false};if(pb<=g.target)return {baseline:first.time,pb,percent:100,remaining:0,met:true};if(first.time<=g.target)return {baseline:first.time,pb,percent:100,remaining:Math.max(0,pb-g.target),met:false};const percent=Math.max(0,Math.min(100,((first.time-pb)/(first.time-g.target))*100));return {baseline:first.time,pb,percent,remaining:Math.max(0,pb-g.target),met:false}}
function buildFilters(){const years=unique(records.map(r=>r.year)).sort((a,b)=>b-a);$('year').innerHTML='<option value="All">All</option>'+years.map(y=>`<option>${y}</option>`).join('');buildDistanceFilter()}
function buildDistanceFilter(){const course=$('course').value;const ds=unique([...records,...goals].filter(x=>course==='All'||x.course===course).map(eventLabel)).sort((a,b)=>distanceSortValue(a)-distanceSortValue(b));const old=$('distance').value;$('distance').innerHTML='<option value="All">All</option>'+ds.map(d=>`<option>${d}</option>`).join('');$('distance').value=ds.includes(old)?old:'All'}
function renderHeader(){const age=currentAge(profile);$('swimmerName').textContent=profile.name;$('swimmerMeta').textContent=[age!=null?`Age ${age}`:null,profile.gender==='F'?'Girls':profile.gender==='M'?'Boys':null,profile.team].filter(Boolean).join(' · ');$('sourceLinkWrap').innerHTML=profile.sourceUrl?`<a class="back-link" href="${escapeHtml(profile.sourceUrl)}" target="_blank" rel="noopener">Source data ↗</a>`:'';document.title=`${profile.name} — Swim Progress`}
function renderMetrics(){const pbs=pbMap(records),meets=unique(records.map(r=>r.meetId||r.meet)),latest=latestRecord(records);$('metricPBs').textContent=pbs.size;$('metricResults').textContent=records.length;$('metricMeets').textContent=meets.length;$('metricLatest').textContent=latest?`${formatDate(latest.date)} · ${eventLabel(latest)}`:'—'}
function renderNextStandards(){const grid=$('nextStandards'),pbs=[...pbMap(records).values()].sort((a,b)=>{const s=STROKE_ORDER.indexOf(a.stroke)-STROKE_ORDER.indexOf(b.stroke);return s||distanceSortValue(a)-distanceSortValue(b)});const cards=[];for(const r of pbs){const t=getStandardTable(r,profile,standards);const ev=evaluateStandard(r.time,t,standards);if(!t||!ev||!ev.next)continue;const denom=Math.max(.01,r.time-(ev.level?t[ev.level]:r.time+Math.max(ev.gap||1,1)));const pct=ev.nextCutoff?Math.max(0,Math.min(100,100-(ev.gap/Math.max(r.time-ev.nextCutoff,1))*10)):0;cards.push(`<article class="next-card"><h3>${escapeHtml(r.stroke)} · ${eventLabel(r)}</h3><div class="row"><span>Current PB</span><strong>${formatSwimTime(r.time)}</strong></div><div class="row"><span>Current</span>${badgeHtml(ev)}</div><div class="next-bar"><span class="next-dot"></span><span class="next-line"></span><span class="badge sb-${ev.next}">${ev.next}</span></div><div class="big">${formatSwimTime(ev.gap)} to ${ev.next}</div><div class="note">Target: ${formatSwimTime(ev.nextCutoff)}</div></article>`)}grid.innerHTML=cards.length?cards.join(''):'<div class="empty">No next-standard targets are available for the swimmer’s configured age group and current events.</div>'}
function pbSource(){const scope=$('pbScope').value,y=$('year').value;if(scope==='SelectedYear'&&y!=='All')return records.filter(r=>String(r.year)===y);return records}
function renderPBs(){let source=pbSource();const f=selected();source=source.filter(r=>(f.stroke==='All'||r.stroke===f.stroke)&&(f.course==='All'||r.course===f.course)&&(f.distance==='All'||eventLabel(r)===f.distance));const cards=[...pbMap(source).values()].sort((a,b)=>{const s=STROKE_ORDER.indexOf(a.stroke)-STROKE_ORDER.indexOf(b.stroke);return s||distanceSortValue(a)-distanceSortValue(b)});$('pbGrid').innerHTML=cards.length?cards.map(r=>{const ev=evaluateStandard(r.time,getStandardTable(r,profile,standards),standards);return `<article class="pb-card"><h3>${escapeHtml(r.stroke)} · ${eventLabel(r)}</h3><div style="font-size:1.6rem;font-weight:800">${formatSwimTime(r.time)}</div><div class="muted">${escapeHtml(r.meet)}<br>${formatDate(r.date)}</div><div class="row"><span>Standard</span>${badgeHtml(ev)}</div>${ev?.next?`<div class="note">Next: ${ev.next} · ${formatSwimTime(ev.gap)} away</div>`:''}</article>`}).join(''):'<div class="empty">No personal bests match the current filters.</div>'}
function renderGoals(){const gs=matchingGoals();$('goalGrid').innerHTML=gs.length?gs.map(g=>{const p=goalProgress(g),ev=p.pb!=null?evaluateStandard(p.pb,getStandardTable(g,profile,standards),standards):null;return `<article class="goal-card"><h3>${escapeHtml(g.stroke)} · ${eventLabel(g)}</h3><div class="muted">${escapeHtml(g.label||'Goal')}</div><div class="row"><span>Current PB</span><strong>${formatSwimTime(p.pb)}</strong></div><div class="row"><span>Target</span><strong>${formatSwimTime(g.target)}</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p.percent.toFixed(1)}%"></div></div><div class="row"><span>Progress</span><strong>${p.percent.toFixed(0)}%</strong></div><div class="row"><span>Remaining</span><strong>${formatSwimTime(p.remaining)}</strong></div><div class="row"><span>Standard</span>${badgeHtml(ev)}</div>${p.met?'<div class="note"><strong>Goal achieved ✓</strong></div>':''}</article>`}).join(''):'<div class="empty">No goals match the current filters.</div>'}
function renderStandards(){const age=currentAge(profile),bracket=getAgeBracket(age,standards),genderLabel=profile.gender==='F'?'Girls':profile.gender==='M'?'Boys':'Unknown';$('standardsNote').innerHTML=bracket?`<strong>${escapeHtml(standards.source||'USA Swimming Motivational Standards')}</strong> · ${bracket.key} ${genderLabel} · age ${age}. Yard records use SCY; meter records use SCM unless a future record explicitly identifies another course.`:`No configured standards bracket is available for age ${age??'unknown'}.`;if(!bracket){$('standardsReference').innerHTML='<div class="empty">No standards available.</div>';return}const sections=[];for(const course of ['SCY','SCM']){const group=standards.courses?.[course]?.[profile.gender]?.[bracket.key];if(!group)continue;const rows=[];for(const stroke of STROKE_ORDER){const dm=group[stroke]||{};for(const d of Object.keys(dm).sort((a,b)=>distanceSortValue(a)-distanceSortValue(b)))rows.push({stroke,d,table:dm[d]})}if(rows.length)sections.push({course,rows})}if(!sections.length){$('standardsReference').innerHTML='<div class="empty">No official standards are embedded for this swimmer’s current bracket.</div>';return}const levels=standards.levels||[];$('standardsReference').innerHTML=sections.map(sec=>`<h3>${sec.course==='SCY'?'Short Course Yards (SCY)':'Short Course Meters (SCM)'}</h3><div class="table-wrap"><table><thead><tr><th>Event</th>${levels.map(l=>`<th>${l}</th>`).join('')}</tr></thead><tbody>${sec.rows.map(x=>{const suffix=x.d.endsWith('Y')?'SCY':'SCM',dist=parseInt(x.d,10),pb=currentPB(x.stroke,suffix,dist),ev=pb!=null?evaluateStandard(pb,x.table,standards):null;return `<tr><td>${escapeHtml(x.stroke)} · ${x.d}${pb!=null?`<div class="note">PB ${formatSwimTime(pb)} · ${badgeHtml(ev)}</div>`:''}</td>${levels.map(l=>`<td>${typeof x.table[l]==='number'?formatTimeOnly(x.table[l]):'—'}</td>`).join('')}</tr>`}).join('')}</tbody></table></div>`).join('')}
function renderHistory(){const rows=filteredRecords().slice().sort((a,b)=>{const c=compareRows(a,b,sortState.field);return sortState.direction==='asc'?c:-c});const pages=Math.max(1,Math.ceil(rows.length/historyPageSize));historyPage=Math.min(Math.max(1,historyPage),pages);const start=(historyPage-1)*historyPageSize,pageRows=rows.slice(start,start+historyPageSize);const tbody=document.querySelector('#historyTable tbody');tbody.innerHTML=pageRows.length?pageRows.map(r=>{const ev=evaluateStandard(r.time,getStandardTable(r,profile,standards,r.age),standards);return `<tr><td>${formatDate(r.date)}</td><td>${r.year}</td><td>${escapeHtml(r.stroke)}</td><td>${eventLabel(r)}</td><td>${formatSwimTime(r.time)}</td><td>${badgeHtml(ev)}</td><td>${escapeHtml(r.meet)}</td></tr>`}).join(''):'<tr><td colspan="7" class="empty">No records match the filters.</td></tr>';$('pageInfo').textContent=`${rows.length?start+1:0}-${Math.min(start+historyPageSize,rows.length)} of ${rows.length} · Page ${historyPage} of ${pages}`;$('firstPage').disabled=$('prevPage').disabled=historyPage<=1;$('nextPage').disabled=$('lastPage').disabled=historyPage>=pages}
function renderCharts(){renderProgressChart(records,progressCourse);renderPBProgress(filteredRecords());renderRadar(goals,goalProgress)}
function renderAll(){renderPBs();renderGoals();renderStandards();renderHistory();renderCharts();renderNextStandards()}
function setupEvents(){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${b.dataset.tab}`));setTimeout(resizeCharts,30)}));document.querySelectorAll('[data-course]').forEach(b=>b.addEventListener('click',()=>{progressCourse=b.dataset.course;document.querySelectorAll('[data-course]').forEach(x=>x.classList.toggle('active',x===b));renderProgressChart(records,progressCourse)}));['year','stroke','distance','pbScope'].forEach(id=>$(id).addEventListener('change',()=>{historyPage=1;renderAll()}));$('course').addEventListener('change',()=>{buildDistanceFilter();historyPage=1;renderAll()});$('pageSize').addEventListener('change',e=>{historyPageSize=Number(e.target.value)||25;historyPage=1;renderHistory()});$('firstPage').onclick=()=>{historyPage=1;renderHistory()};$('prevPage').onclick=()=>{historyPage=Math.max(1,historyPage-1);renderHistory()};$('nextPage').onclick=()=>{historyPage++;renderHistory()};$('lastPage').onclick=()=>{historyPage=Math.max(1,Math.ceil(filteredRecords().length/historyPageSize));renderHistory()};document.querySelectorAll('th[data-field]').forEach(th=>th.addEventListener('click',()=>{const f=th.dataset.field;if(sortState.field===f)sortState.direction=sortState.direction==='asc'?'desc':'asc';else{sortState={field:f,direction:'asc'}}historyPage=1;renderHistory()}))}
try{const params=new URLSearchParams(location.search),cfg=await loadAppConfig();let id=params.get('swimmer')||cfg.defaultSwimmerId;({swimmer:swimmerDoc,goals,standards,directory}=await loadDashboardData(id));profile=swimmerDoc.profile;records=swimmerDoc.records||[];renderHeader();renderMetrics();buildFilters();setupEvents();renderAll();$('loading').classList.add('hide');$('app').classList.remove('hide')}catch(e){$('loading').classList.add('hide');$('error').textContent=`${e.message}. If you opened the HTML directly, start the included local server and open the http://localhost address instead.`;$('error').classList.remove('hide')}
